export const ART_STYLES = [
  "Photorealistic",
  "Impressionism",
  "Expressionism",
  "Surrealism",
  "Cubism",
  "Abstract",
  "Minimalism",
  "Pop Art",
  "Art Nouveau",
  "Art Deco",
  "Renaissance",
  "Baroque",
  "Romanticism",
  "Realism",
  "Pointillism",
  "Fauvism",
  "Futurism",
  "Dadaism",
  "Conceptual Art",
  "Street Art",
  "Graffiti",
  "Anime/Manga",
  "Cartoon",
  "Comic Book",
  "Pixel Art",
  "Low Poly",
  "Vaporwave",
  "Cyberpunk",
  "Steampunk",
  "Dieselpunk",
  "Solarpunk",
  "Gothic",
  "Fantasy",
  "Sci-Fi",
  "Horror",
  "Film Noir",
  "Documentary",
  "Ukiyo-e",
  "Watercolor",
  "Oil Painting",
  "Charcoal Sketch",
  "Pencil Drawing",
  "Ink Wash",
  "Stained Glass",
  "Mosaic",
  "Origami",
  "Claymation",
  "3D Render",
  "Holographic",
];
